[package]
name = "coffee_maker"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
inquire = "0.3"
strum = "0.24"
strum_macros = "0.24"
