name: Rust

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Lint
      run: cargo clippy --color always -- -W clippy::pedantic
    - name: Test
      run: cargo test --verbose
  cd:
    runs-on: ubuntu-latest
    steps:
    - name: Build
      run: cargo build --verbose --release
